### ISSUE TITLE
Identify PR types by prefix in addition to tags

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/github-activity#29]
In the [Executable Book Project dev conventions](https://executablebooks.org/en/latest/contributing.html#releases-and-change-logs) we are using `PREFIX:` to denote different kinds of PRs as opposed to using GitHub tags. I think this is a pretty common use across projects as well, and I wonder if we should support something like this in `github-activity` as well.

For example, we could look for prefixes like:

```
NEW:
IMPROVE:
FIX:
BREAKING:
DEPRECATE:
DOCS:
```

and follow the logic of "if there is a PR tag, that takes precedence. If not, look for a `PREFIX:`.

What do you think @consideRatio ? @chrisjsewell?

**Comment by chrisjsewell** [comment]
+1, also check for plurals DOC/DOCS, FIX/FIXES

**Comment by choldgraf** [comment]
this is now fixed and released!
