### ISSUE TITLE
Support --since <git reference>

### ISSUE THREAD

**Issue by consideRatio** [choldgraf/github-activity#4]
I wanted to use this CLI to get the changes since a given git reference as compared to after a given date. If it is plausible to update to support that, it would be great. I ended up looking at the date of a tagged release manually.

https://github.com/choldgraf/github-activity/blob/95610ab812bb92dbb4a7618e4d0fba76d8a5a001/github_activity/cli.py#L15-L17

https://github.com/choldgraf/github-activity/blob/95610ab812bb92dbb4a7618e4d0fba76d8a5a001/github_activity/github_activity.py#L35-L38

**Comment by choldgraf** [comment]
I think this would be doable by looking up the date corresponding to the ref with an api call, then feeding that value into the search query...it’s using the github search query under the hood, And I don’t think that supports the notion of “issues after a given ref”. Id be +1 on this!
